# Generated by Django 5.1.5 on 2025-04-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_quantity', models.IntegerField()),
                ('product_description', models.CharField(max_length=1000)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='Sellers/ProductImages/')),
            ],
        ),
    ]
