# Generated by Django 5.1.5 on 2025-04-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home'), ('gaming', 'Gaming'), ('health', 'Health'), ('beauty', 'Beauty'), ('more', 'More')], default='more', max_length=20),
        ),
    ]
